# Generated by Django 5.1.2 on 2024-11-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_employee_department_employee_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
    ]
