# Generated by Django 5.1.3 on 2025-01-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('user_status', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_job', models.CharField(blank=True, max_length=100, null=True)),
                ('department_number', models.CharField(blank=True, max_length=50, null=True)),
                ('department_description', models.CharField(blank=True, max_length=200, null=True)),
                ('reports_to', models.CharField(blank=True, max_length=100, null=True)),
                ('reports_to_employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number_1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number_3', models.CharField(blank=True, max_length=15, null=True)),
                ('pay_rule', models.CharField(blank=True, max_length=100, null=True)),
                ('hourly_wage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('worker_type', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule_group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('accrual_profile_name', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
