# Generated by Django 5.1.3 on 2025-01-03 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('MEAL_IN', 'Meal In'), ('MEAL_OUT', 'Meal Out')], max_length=10)),
                ('punch_time', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='api.user')),
            ],
        ),
    ]
