# Generated by Django 5.1.3 on 2025-01-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_is_default_accessprofile_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='function_name',
            field=models.CharField(choices=[('Administration', 'administration.views.admin_home'), ('Manage Timecards', 'manage_timecards.views.dashboard'), ('Punch Management', 'punch.views.punch_list'), ('Reporting', 'reporting.views.generate_reports'), ('User Management', 'administration.views.user_management')], max_length=255),
        ),
    ]
