# Generated by Django 5.1.3 on 2025-01-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_access_profiles_alter_permission_function_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_profiles',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.accessprofile'),
        ),
    ]
