# Generated by Django 5.1.3 on 2025-01-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='access_scope',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_add',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_edit',
        ),
    ]
